import '~/styles/globals.css';
import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { TRPCReactProvider } from '~/trpc/react';
import { headers } from 'next/headers';

const comfortaa = Comfortaa({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`min-h-screen bg-gradient-to-b from-gradient-start to-gradient-end ${comfortaa.className} text-primary-typography text-heading`}
        >
          <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
