import Header from './components/Header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'User Site',
  description: 'Generated by create next app',
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
