import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "User Site",
  description: "Generated by create next app",
};

export default function UserLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Sidebar />
      <main className="ml-72 flex min-h-screen flex-col gap-8 px-10 py-10">
        <Header />
        {children}
      </main>
    </>
  );
}
